---
galaxy_info:
  author: Lenny Shirley II
  description: Converts individual file tree VAR files back into flattened versions to be used directly, or exported back to flattened files
  company: Red Hat
  # issue_tracker_url: http://example.com/issue/tracker
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  # min_ansible_container_version:
  galaxy_tags: []
dependencies: []
...
