---
galaxy_info:
  author: Lenny Shirley II
  description: Converts a flat directory of Ansible variable files (e.g., from an AAP export) into a structured file tree.
  company: Red Hat
  # issue_tracker_url: http://example.com/issue/tracker
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  galaxy_tags: []
dependencies: []
